server:
  port: 8083

spring:  
  application:
    name: userApplication
  logging:
    pattern:
      console: "%msg%n"
    level:
      org.springframework: INFO
      org.hibernate: INFO
  datasource:    
    url: jdbc:mysql://localhost:3306/usersdb?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      connection-timeout: "20000"
      minimum-idle: "5"
      maximum-pool-size: "12"
      idle-timeout: "300000"
      max-lifetime: "1200000"
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.id.new_generator_mappings: "false"
      hibernate.format_sql: "true"
      hibernate.show_sql: false    